version: '3.6'
services:
  database:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=${ZION_DB_USER}
      - POSTGRES_PASSWORD=${ZION_DB_PASSWORD}
      - POSTGRES_DB=${ZION_DB_DATABASE}
    container_name: 'zion-postgres-dev'
  zion:
    build: .
    depends_on:
      - database
    entrypoint: ['sh', '-c','npm run db:migrate:latest && npm run start:prod']
    ports: 
      - ${ZION_APP_PORT}:${ZION_APP_PORT}
    container_name: zion
    environment:
      - ZION_NODE_ENV
      - ZION_APP_PORT
      - ZION_DB_HOST=database
      - ZION_DB_PORT
      - ZION_DB_USER
      - ZION_DB_PASSWORD
      - ZION_DB_DATABASE
      - ZION_JWT_SECRET
      - ZION_JWT_EXPIRES_IN
